COMMON=\
	common/TutoLib.v

STACK=\
	stack/Counter.v \
	stack/Stack.v

CONTAINER=\
	container/ContainerType.v \
	container/ContainerIntro.v \
	container/Container.v

QUEUE=\
	queue/QueueData.v \
	queue/Node.v \
	queue/QueueIntro.v \
	queue/Queue.v \
	queue/AbsQueue.v

FILES=\
	$(COMMON) \
	$(STACK) \
	$(CONTAINER) \
	$(QUEUE)

include ../subdir.mk
